Repository SynergyX-AI-Pattern/SynergyX-ML-Server, pull requests merged in 2025-08, with the labels that each got.

#12 [FIX] 워크플로우에 venv 설치 추가 #9
  .github/workflows/fastapi-dev-ci-cd.yml
Labels: 🚀 ci

#13 [FIX] requirements, batch workers 수정 #9
  app/schedulers/predict_batch_runner.py
  requirements.txt
Labels: 🚀 ci

#14 Bug/#9 deploy error
  app/schemas/base_response.py
Labels: 🚀 ci

#20 [FIX] 예측 배치, 배포 오류 해결 #18
  .github/workflows/fastapi-dev-ci-cd.yml
  app/main.py
  app/schedulers/predict_batch_runner.py
  app/services/batch_service.py
  app/utils/discord_notifier.py
Labels: 🐛 bug

#26 [FIX] requirements 수정 #25
  requirements.txt
Labels: 🐛 bug, 🚀 ci

#29 [DEL] 라우터 삭제 #25
  app/api/v1/routers/__init__.py
Labels: 🐛 bug

#31 [FIX] 이미지 업로드 크기 제한 상향 (5MB -> 20MB) #16
  app/api/v1/endpoints/stocks/image_search.py
Labels: 🐛 bug

#32 Feat/#17 analyze emotion diary
  app/api/v1/endpoints/emotion_diary.py
  app/api/v1/routers/__init__.py
  app/api/v1/routers/emotion_diary_router.py
  app/models/emotion_diary.py
  app/schemas/emotion_diary.py
  app/services/emotion_diary_service.py
  app/services/external/gpt_service.py
  requirements.txt
Labels: ✨ feature

#34 Refactor/#33 update pattern constraints relations
  app/models/pattern_apply.py
  app/models/pattern_detection_log.py
Labels: ♻️ refactor
